#!/usr/bin/env python3
"""Generate demo/seed.sql with realistic fake member data.

Usage:  python3 scripts/generate_demo_seed.py
Output: demo/seed.sql  (checked in; re-run to regenerate)

RNG seeded for reproducibility.
"""

import os
import random
import bcrypt

RNG = random.Random(42)
OUT = os.path.join(os.path.dirname(__file__), '..', 'demo', 'seed.sql')

# Pre-hash the two demo passwords once
ADMIN_HASH = bcrypt.hashpw(b'admin', bcrypt.gensalt(rounds=10)).decode()
USER_HASH  = bcrypt.hashpw(b'user',  bcrypt.gensalt(rounds=10)).decode()
PLACEHOLDER_HASH = bcrypt.hashpw(b'x', bcrypt.gensalt(rounds=4)).decode()

FIRST_NAMES = [
    'James', 'Robert', 'John', 'Michael', 'David', 'William', 'Richard',
    'Joseph', 'Thomas', 'Charles', 'Christopher', 'Daniel', 'Matthew', 'Anthony',
    'Mark', 'Steven', 'Paul', 'Andrew', 'Kenneth', 'George', 'Edward', 'Brian',
    'Ronald', 'Timothy', 'Jason', 'Jeffrey', 'Frank', 'Scott', 'Eric', 'Stephen',
    'Mary', 'Patricia', 'Jennifer', 'Linda', 'Barbara', 'Susan', 'Jessica',
    'Sarah', 'Karen', 'Lisa', 'Nancy', 'Betty', 'Dorothy', 'Sandra', 'Ashley',
    'Margaret', 'Emily', 'Donna', 'Carol', 'Ruth',
]

LAST_NAMES = [
    'Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller',
    'Davis', 'Rodriguez', 'Martinez', 'Hernandez', 'Lopez', 'Gonzalez',
    'Wilson', 'Anderson', 'Thomas', 'Taylor', 'Moore', 'Jackson', 'Martin',
    'Lee', 'Perez', 'Thompson', 'White', 'Harris', 'Sanchez', 'Clark',
    'Ramirez', 'Lewis', 'Robinson', 'Walker', 'Young', 'Allen', 'King',
    'Wright', 'Scott', 'Torres', 'Hill', 'Adams', 'Green', 'Baker',
    'Nelson', 'Hall', 'Rivera', 'Campbell', 'Mitchell', 'Roberts', 'Carter',
    'Phillips', 'Evans',
]

STREETS = [
    'Oak St', 'Maple Ave', 'Cedar Ln', 'Pine Dr', 'Elm Ct', 'Main St',
    'Walnut Blvd', 'Hickory Rd', 'Birch Way', 'Willow Pl', 'Park Ave',
    'Lake Dr', 'Hill Rd', 'Valley View Dr', 'Sunset Blvd', 'Spring St',
    'Church Rd', 'Mill Ln', 'River Rd', 'Forest Dr',
]

CITIES_STATES = [
    ('Indianapolis', 'IN'), ('Fort Wayne', 'IN'), ('Evansville', 'IN'),
    ('South Bend', 'IN'), ('Bloomington', 'IN'), ('Carmel', 'IN'),
    ('Fishers', 'IN'), ('Muncie', 'IN'), ('Terre Haute', 'IN'),
    ('Lafayette', 'IN'), ('Kokomo', 'IN'), ('Anderson', 'IN'),
    ('Columbus', 'IN'), ('Greenwood', 'IN'), ('Noblesville', 'IN'),
    ('Richmond', 'IN'), ('Elkhart', 'IN'), ('New Albany', 'IN'),
    ('Valparaiso', 'IN'), ('Goshen', 'IN'), ('Jeffersonville', 'IN'),
    ('Vincennes', 'IN'), ('Marion', 'IN'), ('Logansport', 'IN'),
    ('Bedford', 'IN'),
]

REPEATERS = [
    '146.7600', '147.0000', '147.2250', '146.8200', '147.1200',
    '146.9400', '145.1100', '147.3450', '146.7000', '145.3500',
    '442.1000', '443.0000', '444.2500', '442.8500', '443.5000',
]

MEMBER_TYPES = ['FULL', 'ASSOCIATE', 'LIFE', 'HONORARY']
MEMBER_TYPE_WEIGHTS = [70, 15, 10, 5]

CALL_PREFIXES = ['W9', 'K9', 'N9', 'WB9', 'KB9', 'KA9', 'WD9', 'KC9', 'KD9', 'KE9']


def random_callsign():
    prefix = RNG.choice(CALL_PREFIXES)
    suffix_len = RNG.choice([2, 3])
    suffix = ''.join(RNG.choice('ABCDEFGHIJKLMNOPQRSTUVWXYZ') for _ in range(suffix_len))
    return f'{prefix}{suffix}'


def random_phone():
    return f'({RNG.randint(200,999)}) {RNG.randint(200,999)}-{RNG.randint(1000,9999)}'


def random_zip():
    return f'{RNG.randint(46001, 47999):05d}'


def esc(val):
    if val is None:
        return 'NULL'
    s = str(val).replace("\\", "\\\\").replace("'", "\\'")
    return f"'{s}'"


def main():
    lines = [
        '-- DO NOT EDIT — generated by scripts/generate_demo_seed.py',
        '-- Re-run the script to regenerate.',
        '',
        'SET FOREIGN_KEY_CHECKS = 0;',
        'TRUNCATE TABLE webauthn_credentials;',
        'TRUNCATE TABLE totp_backup_codes;',
        'TRUNCATE TABLE password_reset_tokens;',
        'TRUNCATE TABLE members;',
        'SET FOREIGN_KEY_CHECKS = 1;',
        '',
    ]

    callsigns_used = set()
    members = []

    # Fixed demo accounts
    members.append({
        'call_sign': 'ADMIN',
        'password_hash': ADMIN_HASH,
        'email': 'admin@demo.example',
        'name': 'Demo Administrator',
        'primary_rep': '146.7600',
        'rep_call': 'W9IRC',
        'address': '100 Main St',
        'city': 'Indianapolis',
        'state': 'IN',
        'zip': '46204',
        'telephone': '(317) 555-0001',
        'paid_thru': '9999',
        'member_type': 'LIFE',
        'is_admin': 1,
        'admin_comments': None,
        'expiration_status': 'active',
    })
    callsigns_used.add('ADMIN')

    members.append({
        'call_sign': 'USER',
        'password_hash': USER_HASH,
        'email': 'user@demo.example',
        'name': 'Demo Member',
        'primary_rep': '147.0000',
        'rep_call': 'W9IRC',
        'address': '200 Elm St',
        'city': 'Fort Wayne',
        'state': 'IN',
        'zip': '46802',
        'telephone': '(260) 555-0002',
        'paid_thru': '2026',
        'member_type': 'FULL',
        'is_admin': 0,
        'admin_comments': None,
        'expiration_status': 'active',
    })
    callsigns_used.add('USER')

    # Generate 100 random members
    for _ in range(100):
        cs = random_callsign()
        while cs in callsigns_used:
            cs = random_callsign()
        callsigns_used.add(cs)

        fname = RNG.choice(FIRST_NAMES)
        lname = RNG.choice(LAST_NAMES)
        city, state = RNG.choice(CITIES_STATES)
        mtype = RNG.choices(MEMBER_TYPES, weights=MEMBER_TYPE_WEIGHTS, k=1)[0]

        # Determine paid_thru and expiration status
        if mtype in ('LIFE', 'HONORARY'):
            paid_thru = '9999'
            exp_status = 'active'
        else:
            year = RNG.choice([2024, 2024, 2025, 2025, 2026, 2026, 2026, 2027, 2027, 2028])
            paid_thru = str(year)
            if year > 2026:
                exp_status = 'active'
            elif year == 2026:
                exp_status = 'expiring'
            else:
                exp_status = 'expired'

        members.append({
            'call_sign': cs,
            'password_hash': PLACEHOLDER_HASH,
            'email': f'{cs.lower()}@demo.example',
            'name': f'{fname} {lname}',
            'primary_rep': RNG.choice(REPEATERS),
            'rep_call': RNG.choice(['W9IRC', 'W9VU', 'W9IMS', 'K9RU', None]),
            'address': f'{RNG.randint(100,9999)} {RNG.choice(STREETS)}',
            'city': city,
            'state': state,
            'zip': random_zip(),
            'telephone': random_phone(),
            'paid_thru': paid_thru,
            'member_type': mtype,
            'is_admin': 0,
            'admin_comments': RNG.choice([None, None, None, 'Board member', 'New member 2025', 'Needs follow-up']),
            'expiration_status': exp_status,
        })

    # Build INSERT statements
    cols = [
        'call_sign', 'password_hash', 'email', 'name', 'primary_rep', 'rep_call',
        'address', 'city', 'state', 'zip', 'telephone', 'paid_thru', 'member_type',
        'is_admin', 'admin_comments', 'expiration_status',
    ]

    for m in members:
        vals = ', '.join(esc(m[c]) for c in cols)
        lines.append(f"INSERT INTO members ({', '.join(cols)}) VALUES ({vals});")

    lines.append('')

    with open(OUT, 'w') as f:
        f.write('\n'.join(lines))

    print(f'Wrote {len(members)} members to {OUT}')


if __name__ == '__main__':
    main()
